### ISSUE TITLE
Imágenes no se ven en el post Props y State

### ISSUE THREAD

**Issue by marcorichetta** [agustinmulet/reactworkshop#1]
En el post https://agustinmulet.github.io/reactworkshop/props-y-state/ las imágenes no se ven aunque en el DOM están.

![imagen](https://user-images.githubusercontent.com/19599150/57489958-13864580-728e-11e9-8b2a-a9d1888bb56d.png)

Cambiándole el atributo `position` a initial o relative si me las muestra, pero obvio que es a mano.

Entiendo que las páginas se generan desde el mdx en `src/pages` pero no sé como corregirlo.

**Comment by agustinmulet** [comment]
Hola @marcorichetta, perdón que recién veo el issue, gracias por reportarlo!
Estoy viendo que casualmente son las únicas dos imágenes en JPG así que es probable que venga por ahí el problema, voy a pasarlas a PNG como workaround, estoy teniendo un par de problemas para hacer el deploy, una vez que logre hacerlo vemos si se arregla

**Comment by marcorichetta** [comment]
Hola Agustín, buenísimo que lo puedas corregir y gracias a vos por el contenido.

Respecto al deploy, nunca pude hacerlo porque no me muestra los repos de github para linkear desde netlify, después de que te pide la autorización. 
No se si te pasará lo mismo pero creo que tiene que ver con Firefox y alguna extensión que esté bloqueando algo pero creo haber probado con todo desactivado y tampoco me dejó.

**Comment by agustinmulet** [comment]
Marco, ahí pude hacer el deploy, parece que hay un tema con las últimas versiones de Gatsby y `gatsby-images` pero pude cambiarlas a PNG y puedo verlas ahora.
Confirmame si vos también podés verlas bien y cierro el issue 😁

**Comment by marcorichetta** [comment]
La verdad nunca me pasó con otras páginas creo.
Ahora se ven así, como una línea en donde está la imagen solamente.
Cambiando `display:flex o grid` las puedo ver.
***
![imagen](https://user-images.githubusercontent.com/19599150/60552357-dc1f9c80-9d04-11e9-8825-eefe5d1248a3.png)
***
![imagen](https://user-images.githubusercontent.com/19599150/60552303-9f53a580-9d04-11e9-9fde-d16e78f33829.png)

Estoy usando Firefox 67.0.4 en Linux por las dudas.

**Comment by agustinmulet** [comment]
Uh sí, voy a tener que ver más a fondo el error ese. Pasa cuando entrás directo por la URL, si vas para atrás y volvés usando los botones que están al fondo de cada paso, se muestran como deberían.
Este finde que es largo voy a ver si puedo encontrar por qué pasa eso. Gracias!

**Comment by marcorichetta** [comment]
Efectivamente, pasa lo que decís.
No te quiero meter presión pero parece que largaron la [v2](https://codebushi.com/using-gatsby-image/) de gatsby-image hace unos días jaja (Suponiendo que viene por ahí el problema).

Cualquier cosa estoy para ayudar.

**Comment by agustinmulet** [comment]
Hola Marco! Perdoname por el tiempo que me tomé para algo tan simple. Te hice caso y le agregué `display: flex` y tuve que mandar `position: relative !important`, es un workaround pero funciona. Vi un tuit sobre imágenes en los MDX para mejorar este tema y no dejarlo así pero cuando tenga tiempo lo veo bien.

Avisame si podés reproducir el error todavía, yo lo probé en Opera y Firefox y lo veo bien, gracias por la buena onda

**Comment by marcorichetta** [comment]
Hola Agustín.

No me pidas perdón, estás brindando tu tiempo para enseñar así que lo menos que puedo hacer es ayudarte.

Ahora si se ven las imágenes de ambas formas. :+1:
El único issue es que si navegas para atrás y adelante con los botones al final de cada paso, se muestra un espacio en blanco del tamaño de la imagen y después la imágen. (Creo que esto es mejor a que no se muestre la imagen directamente)

**Comment by agustinmulet** [comment]
Hola @marcorichetta, al fin me tomé un rato y por lo que estuve viendo, el plugin de gatsby para mdx tiene un problema al querer mostrar las imágenes inline, lo comprobé haciendo un proyecto de cero y hace eso del espacio en blanco, es un error del blur-up (el efecto de las imágenes). Terminé usando las imágenes con un componente que usa `gatsby-image` y también cambié las `react-tabs` por `@reach/tabs` que se habían roto al haber actualizado paquetes.
Según probé en Opera y Firefox, no puedo reproducir el error, así que si podés confirmame si a vos tampoco te pasa y pusheo los cambios a master. Gracias por bancarme!

**Comment by marcorichetta** [comment]
La verdad me hubiese encantado ayudar pero nunca usé ni gatsby ni mdx así que me iba a costar bastante jaja
De todas las formas que probé funciona perfecto.
Gracias a vos por solucionarlo y espero mucha más gente lo pueda aprovechar!

**Comment by agustinmulet** [comment]
Buenísimo :) cierro el bug entonces, cualquier otra cosa que veas no dudes en reportarla!
